########################
#                      #
#       Announce       #
#                      #
########################


#Made by XingYan

announce: "NONE"
discord:
  enable: true
  channel: "803202946267086911"
message:
  prefix: "&c[公告]"